"""Symbol normalization, classification, and tenant isolation."""

from __future__ import annotations

import pytest

from app.core.enums import AssetClass
from app.services.instruments import (
    classify_symbol,
    link_broker_symbol,
    normalize_symbol,
    resolve_broker_symbol,
    upsert_instrument,
)


@pytest.mark.parametrize(
    "raw,expected",
    [
        ("EURUSD", "EURUSD"),
        ("eurusd", "EURUSD"),
        ("EURUSD.m", "EURUSD"),
        ("EURUSD-ECN", "EURUSD"),
        ("EURUSD_micro", "EURUSD"),
        ("XAUUSD#", "XAUUSD"),
        ("BTC/USD", "BTCUSD"),
    ],
)
def test_normalize_symbol(raw, expected):
    assert normalize_symbol(raw) == expected


@pytest.mark.parametrize(
    "symbol,asset_class,base,quote",
    [
        ("EURUSD", AssetClass.FOREX, "EUR", "USD"),
        ("XAUUSD", AssetClass.METAL, "XAU", "USD"),
        ("BTCUSD", AssetClass.CRYPTO, "BTC", "USD"),
        ("BTCUSDT", AssetClass.CRYPTO, "BTC", "USDT"),
    ],
)
def test_classify_known_shapes(symbol, asset_class, base, quote):
    assert classify_symbol(symbol) == (asset_class, base, quote)


def test_unknown_symbol_is_not_guessed():
    """An unrecognised shape returns OTHER rather than a plausible invention."""
    assert classify_symbol("US500") == (AssetClass.OTHER, None, None)


def test_upsert_instrument_is_idempotent(session):
    first = upsert_instrument(session, "EURUSD.m")
    second = upsert_instrument(session, "eurusd")

    assert first.id == second.id
    assert first.symbol == "EURUSD"
    assert first.asset_class == AssetClass.FOREX


def test_upsert_does_not_overwrite_curated_values(session):
    instrument = upsert_instrument(session, "EURUSD", name="Curated name")
    upsert_instrument(session, "EURUSD", name="Autogenerated")

    assert instrument.name == "Curated name"


def test_broker_symbol_properties_are_stored_verbatim(session, tenant):
    mapping = link_broker_symbol(
        session,
        tenant.id,
        "acme-mt5",
        "EURUSD.m",
        contract_size=100_000,
        digits=5,
        point=0.00001,
        tick_value=1.0,
    )

    assert mapping.raw_symbol == "EURUSD.m"
    assert float(mapping.contract_size) == 100_000
    assert mapping.digits == 5


def test_broker_symbols_are_tenant_isolated(session, tenant, other_tenant):
    """One tenant's broker mapping must be invisible to another."""
    link_broker_symbol(session, tenant.id, "acme-mt5", "EURUSD.m", contract_size=100_000)

    mine = resolve_broker_symbol(session, tenant.id, "acme-mt5", "EURUSD.m")
    theirs = resolve_broker_symbol(session, other_tenant.id, "acme-mt5", "EURUSD.m")

    assert mine is not None
    assert theirs is None


def test_two_tenants_share_the_canonical_instrument(session, tenant, other_tenant):
    a = link_broker_symbol(session, tenant.id, "acme-mt5", "EURUSD.m")
    b = link_broker_symbol(session, other_tenant.id, "globex-ctrader", "EURUSD-ECN")

    assert a.instrument_id == b.instrument_id
