"""Symbol normalization, classification, and tenant isolation."""

from __future__ import annotations

import pytest

from app.core.enums import AssetClass
from app.services.instruments import (
    classify_symbol,
    link_broker_symbol,
    normalize_symbol,
    resolve_broker_symbol,
    upsert_instrument,
)


@pytest.mark.parametrize(
    "raw,expected",
    [
        ("EURUSD", "EURUSD"),
        ("eurusd", "EURUSD"),
        ("EURUSD.m", "EURUSD"),
        ("EURUSD-ECN", "EURUSD"),
        ("EURUSD_micro", "EURUSD"),
        ("XAUUSD#", "XAUUSD"),
        ("BTC/USD", "BTCUSD"),
        # Six-character pairs ending in a letter the decoration list also uses.
        # Every case above carries a separator, which is why the bare-letter
        # branch went eleven months without being exercised and USDINR sat in
        # production as USDIN.
        ("USDINR", "USDINR"),
        ("USDZAR", "USDZAR"),
        ("USDIDR", "USDIDR"),
        ("EURCZK", "EURCZK"),
        ("USDMYR", "USDMYR"),
        # Still stripped: seven characters, so the sixth is not the last.
        ("EURUSDm", "EURUSD"),
        ("USDINR.m", "USDINR"),
        ("USDZAR-ECN", "USDZAR"),
    ],
)
def test_normalize_symbol(raw, expected):
    assert normalize_symbol(raw) == expected


@pytest.mark.parametrize(
    "symbol,asset_class,base,quote",
    [
        ("EURUSD", AssetClass.FOREX, "EUR", "USD"),
        ("XAUUSD", AssetClass.METAL, "XAU", "USD"),
        ("BTCUSD", AssetClass.CRYPTO, "BTC", "USD"),
        ("BTCUSDT", AssetClass.CRYPTO, "BTC", "USDT"),
    ],
)
def test_classify_known_shapes(symbol, asset_class, base, quote):
    assert classify_symbol(symbol) == (asset_class, base, quote)


def test_unknown_symbol_is_not_guessed():
    """An unrecognised shape returns OTHER rather than a plausible invention."""
    assert classify_symbol("US500") == (AssetClass.OTHER, None, None)


def test_upsert_instrument_is_idempotent(session):
    first = upsert_instrument(session, "EURUSD.m")
    second = upsert_instrument(session, "eurusd")

    assert first.id == second.id
    assert first.symbol == "EURUSD"
    assert first.asset_class == AssetClass.FOREX


def test_upsert_does_not_overwrite_curated_values(session):
    instrument = upsert_instrument(session, "EURUSD", name="Curated name")
    upsert_instrument(session, "EURUSD", name="Autogenerated")

    assert instrument.name == "Curated name"


def test_broker_symbol_properties_are_stored_verbatim(session, tenant):
    mapping = link_broker_symbol(
        session,
        tenant.id,
        "acme-mt5",
        "EURUSD.m",
        contract_size=100_000,
        digits=5,
        point=0.00001,
        tick_value=1.0,
    )

    assert mapping.raw_symbol == "EURUSD.m"
    assert float(mapping.contract_size) == 100_000
    assert mapping.digits == 5


def test_broker_symbols_are_tenant_isolated(session, tenant, other_tenant):
    """One tenant's broker mapping must be invisible to another."""
    link_broker_symbol(session, tenant.id, "acme-mt5", "EURUSD.m", contract_size=100_000)

    mine = resolve_broker_symbol(session, tenant.id, "acme-mt5", "EURUSD.m")
    theirs = resolve_broker_symbol(session, other_tenant.id, "acme-mt5", "EURUSD.m")

    assert mine is not None
    assert theirs is None


def test_two_tenants_share_the_canonical_instrument(session, tenant, other_tenant):
    a = link_broker_symbol(session, tenant.id, "acme-mt5", "EURUSD.m")
    b = link_broker_symbol(session, other_tenant.id, "globex-ctrader", "EURUSD-ECN")

    assert a.instrument_id == b.instrument_id


class TestCurrencyLegsAreVisibleToTheRiskLayer:
    """`classify_symbol` fills `base_currency` and `quote_currency`, and
    `portfolio.py` reads currency exposure from exactly those two columns.

    A pair whose quote is not recognised comes back `other` with both columns
    empty, and its dollar leg then contributes nothing to the currency cap.
    Four instruments on the deployed watchlist were in that state: correctly
    spelled, correctly ingested, and invisible to the one limit that exists to
    stop the whole book being a single bet on one currency.
    """

    @pytest.mark.parametrize(
        "symbol", ["USDCZK", "USDHUF", "USDILS", "USDTHB", "USDINR", "USDZAR"]
    )
    def test_a_deployed_pair_reports_both_legs(self, symbol):
        asset_class, base, quote = classify_symbol(symbol)

        assert asset_class is AssetClass.FOREX
        assert base == symbol[:3]
        assert quote == symbol[3:]

    def test_an_unrecognised_shape_still_refuses_to_guess(self):
        """Widening the set must not turn the classifier into something that
        invents a currency for anything six characters long."""
        asset_class, base, quote = classify_symbol("ZZZQQQ")

        assert asset_class is AssetClass.OTHER
        assert base is None
        assert quote is None
